version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hectoclash
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
      - redis
    networks:
      - hectoclash-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hectoclash-network

  # PostgreSQL database
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hectoclash
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hectoclash-network

  # Redis for caching and real-time features
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - hectoclash-network

networks:
  hectoclash-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
